services:
  db:
    image: postgres:14.6
    container_name: fastapi_todo_app_db 
    # image: pgvector/pgvector:pg17
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DATABASES: "fastapi_todo_app_db"
    ports:
      - 7653:5432
    volumes:
      # - ./init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh
      - db_volume:/var/lib/postgresql/data

volumes:
  db_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.data
