set shell := ["bash", "-c"]
set dotenv-load := true
set allow-duplicate-recipes
set positional-arguments
set export
# set quiet

# aws python repo
# export profile := "vuvuzella"
# export domain := env('AWS_CODEARTIFACT_DOMAIN', "test_codeartifact_domain")
# export domain_owner := env('AWS_ACCOUNT_ID', "test_aws_account_id")
# export region := env('AWS_REGION', "test_aws_region")
# 
# get_auth_codeartifact_cli := "aws codeartifact get-authorization-token --domain $1 --domain-owner $2 --region $3 --output text | awk -F' ' '{print $1}'"
# 
# code_artifact_token := shell(get_auth_codeartifact_cli, domain, domain_owner, region)
# export AWS_CODEARTIFACT_TOKEN := code_artifact_token
# export UV_INDEX_CODEARTIFACT_USERNAME := "aws"
# export UV_INDEX_CODEARTIFACT_PASSWORD := code_artifact_token
# export UV_PUBLISH_USERNAME := "aws"
# export UV_PUBLISH_PASSWORD := code_artifact_token

# make sure to configure this profile as the default profile
login profile="vuvuzella":
    aws login --profile {{ profile }}

token:
    echo $AWS_CODEARTIFACT_TOKEN | xsel --clipboard --input

add +package:
    uv add {{ package }} 

add-dev +package:
    uv add {{ package }} --group dev

install:
    uv sync

_migrate_upgrade version:
    uv run alembic upgrade '{{ version }}'

_migrate_downgrade version:
    uv run alembic downgrade '{{ version }}'

_migrate_revision label:
    uv run alembic revision -m '{{ label }}'

migrate command="upgrade" version="head":
    case {{ command }} in \
        upgrade) just _migrate_upgrade '{{ version }}';; \
        downgrade) just _migrate_downgrade '{{ version }}';; \
        revision) just _migrate_revision '{{ version }}';; \
        *) uv run alembic {{ command }} '{{ version }}';; \
    esac


test type="unit":
    uv run pytest ./tests/{{ type }} -vvsrP
    # uv run pytest ./tests -vvsrP

build:
    uv build

publish:
    uv publish --index codeartifact


default:
    just --list
